modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="warproject"
version="1.0.0"
displayName="War Project - Okop (Trench Fortification)"
description='''
Realistic trench fortification mod for Minecraft.
Build and reinforce trenches with support beams, camo nets, sandbags, barbed wire, firing slots, and more.
'''
authors="FrostLogicDev"

[[dependencies.warproject]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.warproject]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
